services:
  bot:
    image: aya_bot
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=${DB_PATH}
      - ADMIN_ID=${ADMIN_ID}
    container_name: aya_bot_container
    env_file:
      - .env
    restart: always